backend/core/urls.py
from django.urls import path

from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

backend/exam/urls.py
from django.urls import path

from backend.exam import views as v

app_name = 'exam'

urlpatterns = [
    path('', v.care_list, name='care_list'),
    path('create/', v.care_create, name='care_create'),
    path('<int:pk>/', v.care_detail, name='care_detail'),
    path('<int:pk>/update/', v.care_update, name='care_update'),
    path('<int:pk>/update/exam/', v.care_update_exam, name='care_update_exam'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('exam/', include('backend.exam.urls', namespace='exam')),
    path('admin/', admin.site.urls),
]

backend/core/models.py
from django.db import models

# Create your models here.

backend/exam/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy


class Patient(models.Model):
    registration = models.CharField('matrícula', max_length=7, unique=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='paciente',
        related_name='patients'
    )

    class Meta:
        ordering = ('user__first_name',)
        verbose_name = 'paciente'
        verbose_name_plural = 'pacientes'

    def __str__(self):
        return f'{self.user.first_name}'

    # def get_absolute_url(self):
    #     return reverse_lazy('_detail', kwargs={'pk': self.pk})


class Exam(models.Model):
    title = models.CharField('título', max_length=50, unique=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'exame'
        verbose_name_plural = 'exames'

    def __str__(self):
        return f'{self.title}'

    # def get_absolute_url(self):
    #     return reverse_lazy('_detail', kwargs={'pk': self.pk})


class Care(models.Model):
    doctor = models.CharField('médico', max_length=100)
    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name='paciente',
        related_name='cares',
    )
    created = models.DateTimeField('data', auto_now_add=True)

    class Meta:
        ordering = ('doctor',)
        verbose_name = 'atendimento'
        verbose_name_plural = 'atendimentos'

    def __str__(self):
        return f'{self.doctor}'

    def get_absolute_url(self):
        return reverse_lazy('exam:care_detail', kwargs={'pk': self.pk})


class CareItems(models.Model):
    care = models.ForeignKey(
        Care,
        on_delete=models.CASCADE,
        verbose_name='atendimento',
        related_name='care_items',
    )
    exam = models.ForeignKey(
        Exam,
        on_delete=models.CASCADE,
        verbose_name='exame',
        related_name='care_items_exam',
    )
    is_done = models.BooleanField('feito?', default=False)

    class Meta:
        ordering = ('pk',)
        verbose_name = 'atendimento item'
        verbose_name_plural = 'atendimento itens'

    def __str__(self):
        return f'{self.pk}'

        # def get_absolute_url(self):
        #     return reverse_lazy('_detail', kwargs={'pk': self.pk})

backend/exam/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.urls import reverse

from .models import Care, CareItems


class CareForm(forms.ModelForm):
    id = forms.IntegerField(required=False)

    class Meta:
        model = Care
        fields = ('id', 'doctor', 'patient')

    def __init__(self, *args, **kwargs):
        super(CareForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.disabled = True

        self.fields['id'].label = ''
        self.fields['id'].widget = forms.HiddenInput()


class CareItemsForm(forms.ModelForm):
    id = forms.IntegerField()

    class Meta:
        model = CareItems
        fields = ('care', 'id', 'exam', 'is_done')

    def __init__(self, *args, **kwargs):
        super(CareItemsForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['care'].label = ''
        self.fields['care'].widget = forms.HiddenInput()

        self.fields['id'].label = ''
        self.fields['id'].widget = forms.HiddenInput()

        self.fields['exam'].disabled = True

        pk = reverse('exam:care_update_exam', kwargs={'pk': self.instance.pk})
        self.fields['is_done'].widget.attrs['hx-get'] = f'{pk}'
        self.fields['is_done'].widget.attrs['hx-swap'] = f'none'


CareItemsFormset = inlineformset_factory(
    Care,
    CareItems,
    form=CareItemsForm,
    extra=0,
    can_delete=False,
    min_num=1,
    validate_min=True,
)

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/exam/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import CareForm, CareItemsFormset
from .models import Care, CareItems, Exam


def care_list(request):
    template_name = 'exam/care_list.html'
    object_list = Care.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)


def care_create(request):
    template_name = 'exam/care_create.html'
    form = CareForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            # Salva o atendimento
            care = form.save()
            exams = Exam.objects.all()
            aux = []
            for exam in exams:
                care_items = CareItems(
                    care=care,
                    exam=exam
                )
                aux.append(care_items)
            CareItems.objects.bulk_create(aux)

            return redirect('exam:care_list')

    context = {'form': form}
    return render(request, template_name, context)


def care_detail(request, pk):
    template_name = 'exam/care_detail.html'
    obj = Care.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def care_update(request, pk):
    template_name = 'exam/care_update.html'
    care_instance = Care.objects.get(pk=pk)

    form = CareForm(request.POST or None, instance=care_instance, prefix='main')
    formset = CareItemsFormset(request.POST or None, instance=care_instance, prefix='items')

    context = {'form': form, 'formset': formset}
    return render(request, template_name, context)


def care_update_exam(request, pk):
    '''
    Atualiza cada exame marcando is_done como True ou False.
    '''
    care_items = CareItems.objects.get(pk=pk)
    # Verifica se a lista com os valores do request tem alguma coisa ou
    # se a lista vem vazia.
    is_done_list = list(request.GET.values())

    if is_done_list:
        is_done = True
    else:
        is_done = False

    care_items.is_done = is_done
    care_items.save()
    return HttpResponse(pk)

backend/core/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Django</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block css %}{% endblock css %}

</head>

<body>
  <div class="container">
    {% include "includes/nav.html" %}
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap core JS -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script src="https://unpkg.com/htmx.org@1.6.1"></script>
</body>

</html>

backend/core/templates/includes/nav.html
<!-- includes/nav.html -->
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'exam:care_list' %}">Exames</a>
      </li>
    </ul>
  </div>
</nav>

backend/core/templates/index.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>Exames médicos</h1>
    <a href="https://gitlab.com/rg3915/exame-inline" target="_blank">Exame inline</a>
  </div>
{% endblock content %}

backend/exam/templates/exam/care_create.html
{% extends "base.html" %}

{% block content %}

<h1>Novo atendimento</h1>

<div class="row">
  <div class="col-sm-6">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button
        class="btn btn-primary"
        type="submit"
      >Salvar</button>
    </form>
  </div>
</div>

{% endblock content %}

backend/exam/templates/exam/care_detail.html
{% extends "base.html" %}

{% block content %}

<h1>
  Exame médico
  <a href="{% url 'exam:care_update' object.pk %}" class="btn btn-success">Editar</a>
</h1>

<div class="row">
  <div class="cols">
    <table class="table">
      <thead>
        <tr>
          <th>Doutor</th>
          <th>Paciente</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ object.doctor }}</td>
          <td>{{ object.patient }}</td>
        </tr>
        <tr>
          <th>Exame</th>
          <th>Feito?</th>
        </tr>
        {% for obj in object.care_items.all %}
          <tr>
            <td>{{ obj.exam }}</td>
            <td>
              {% if obj.is_done %}
                <span>
                  <i class="fa fa-check" style="color: green"></i>
                </span>
              {% else %}
                  <i class="fa fa-times" style="color: red"></i>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

backend/exam/templates/exam/care_list.html
{% extends "base.html" %}

{% block content %}

<h1>
  Exames médicos
  <a href="{% url 'exam:care_create' %}" class="btn btn-primary">Criar Atendimento</a>
</h1>

<div class="row">
  <div class="cols">
    <table class="table">
      <thead>
        <tr>
          <th>Médico</th>
          <th>Paciente</th>
          <th>Data</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.doctor }}</a>
            </td>
            <td>{{ object.patient }}</td>
            <td>{{ object.created }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

backend/exam/templates/exam/care_update.html
{% extends "base.html" %}
{% load static %}

{% block css %}

<style>
  .form-control {
    margin: 10px;
  }
</style>

{% endblock css %}

{% block content %}

<h1>Editar atendimento</h1>

<div class="row">
  <div class="cols">
    <form method="POST" novalidate>
      {% csrf_token %}

      {{ form.as_p }}

      {{ formset.management_form }}

      <div class="row">
        <div class="cols">

          <legend>Itens</legend>

          {% for care_item_form in formset %}
            <div id="care" class="form-inline">
              <div id="item-{{ forloop.counter0 }}" class="form-group">
                {{ care_item_form.care }}
                {{ care_item_form.id }}

                {{ care_item_form.exam.label }}
                {{ care_item_form.exam }}

                {{ care_item_form.is_done.label }}
                {{ care_item_form.is_done }}  <!-- Os atributos hx-get, hx-swap estão definidos no forms.py -->
              </div>
            </div>
          {% endfor %}

        </div>
      </div>

    </form>

    <a href="{% url 'exam:care_detail' form.id.value %}" class="btn btn-primary">Fechar</a>
  </div>
</div>

{% endblock content %}